#服务器的配置
server:
  #修改服务器的端口
  port: 8090
#配置spring
spring:
  mvc:
    #配置访问静态资源
    static-path-pattern: /static/**

  #数据源的配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/uuuu?useUnicode=true&characterEncoding=utf-8
      username: root
      password:

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置相关的mybatis
mybatis:
  #扫描加载到所有的mapper.xml文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl